version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8-node-browsers
        environment:
          ## this enables colors in the output
          TERM: xterm
          NODE_OPTIONS: --max-old-space-size=2048
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm ci --unsafe-perm
      - save_cache:
          key: npm-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/app/node_modules/
            - /home/circleci/.cache/Cypress
      - run: npm run test:ci
      - store_artifacts:
          path: /home/circleci/app/cypress/screenshots/
  build_python:
    docker:
      - image: circleci/python:3.8
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run linter for Python sources
          command: flake8 satellite
      - run:
          name: Run Python unit tests
          command: pytest satellite/tests
  smoketest:
    docker:
      - image: circleci/python:3.8-node-browsers
        environment:
          TERM: xterm
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm ci --unsafe-perm
      - save_cache:
          key: npm-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/app/node_modules/
            - /home/circleci/.cache/Cypress
      - run:
          name: Test YAML Consistency
          command: |
            CYPRESS_BASE_URL=https://dashboard.$VGS_DASHBOARD_DOMAIN \
            CYPRESS_VGS_DASHBOARD_DOMAIN=$VGS_DASHBOARD_DOMAIN \
            CYPRESS_VGS_DASHBOARD_EMAIL=$VGS_DASHBOARD_EMAIL \
            CYPRESS_VGS_DASHBOARD_PASS=$VGS_DASHBOARD_PASS \
            npm run cy:smoke
      - store_artifacts:
          path: /home/circleci/app/cypress/screenshots/


workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - build_python
  # periodical_smoke_test:
  #   ## create dashboard route by uploading satellite-generated YAML
  #   triggers:
  #     - schedule:
  #         cron: "0 8 * * *"
  #         filters:
  #           branches:
  #             only:
  #               - master
  #   jobs:
  #     - smoketest
